/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#7cf994",
        "on-tertiary-fixed-variant": "#93000b",
        secondary: "#006e2d",
        "on-primary-fixed-variant": "#264191",
        outline: "#757682",
        "secondary-fixed-dim": "#62df7d",
        "on-secondary-container": "#007230",
        tertiary: "#5d0004",
        "on-tertiary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-error": "#ffffff",
        "surface-variant": "#dce2f7",
        "on-tertiary-fixed": "#410002",
        "tertiary-container": "#87000a",
        "on-background": "#141b2b",
        "on-primary-container": "#90a8ff",
        error: "#ba1a1a",
        "on-tertiary-container": "#ff8b80",
        "surface-container": "#e9edff",
        "primary-fixed": "#dce1ff",
        "surface-container-highest": "#dce2f7",
        "outline-variant": "#c5c5d3",
        "on-secondary-fixed": "#002109",
        "surface-container-low": "#f1f3ff",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#edf0ff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#4059aa",
        surface: "#f9f9ff",
        "surface-container-high": "#e1e8fd",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005320",
        "tertiary-fixed-dim": "#ffb4ab",
        "inverse-surface": "#293040",
        "primary-fixed-dim": "#b6c4ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#141b2b",
        background: "#f9f9ff",
        "on-surface-variant": "#444651",
        "on-primary-fixed": "#00164e",
        "surface-dim": "#d3daef",
        "secondary-fixed": "#7ffc97",
        "tertiary-fixed": "#ffdad6",
        "inverse-primary": "#b6c4ff",
        primary: "#00236f",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
